Trisatech.MWorkforce.Cms/ViewModels/SurveyViewModel.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Trisatech.MWorkforce.Cms.ViewModels
{
    public class SurveyViewModel
    {
        [JsonProperty("survey_id")]
        public string SurveyId { get; set; }
        [Display(Name = "Name")]
        [JsonProperty("name")]
        [Required]
        public string SurveyName { get; set; }
        [Display(Name = "Google Form Link")]
        [JsonProperty("link")]
        [Required]
        public string SurveyLink { get; set; }
        [Display(Name = "Start date")]
        [JsonProperty("start_date")]
        [Required]
        public DateTime StartDate { get; set; }
        [Display(Name = "End date")]
        [JsonProperty("end_date")]
        [Required]
        public DateTime EndDate { get; set; }
    }
}

Trisatech.MWorkforce.Cms/Controllers/SurveyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Trisatech.MWorkforce.Business.Entities;
using Trisatech.MWorkforce.Business.Interfaces;
using Trisatech.MWorkforce.Cms.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Filters;
using Trisatech.AspNet.Common.Helpers;

namespace Trisatech.MWorkforce.Cms.Controllers
{
    [Authorize]
    public class SurveyController : Controller
    {
        private readonly ISurveyService surveyService;
        public SurveyController(ISurveyService surveyService)
        {
            this.surveyService = surveyService;
        }

        public override void OnActionExecuted(ActionExecutedContext context)
        {
            ViewBag.SelectedMenu = "survey";

            base.OnActionExecuted(context);
        }

        // GET: Survey
        public ActionResult Index()
        {
            return View();
        }

        // GET: Survey/Details/5
        public ActionResult Details(string id)
        {
            if (string.IsNullOrEmpty(id))
                return NotFound();

            var result = surveyService.Get(id);
            if (result == null)
                return NotFound();
            
            SurveyViewModel surveyViewModel = new SurveyViewModel();
            CopyProperty.CopyPropertiesTo(result, surveyViewModel);
            surveyViewModel.StartDate.ToLocalTime();
            surveyViewModel.EndDate.ToLocalTime();

            return View(surveyViewModel);
        }

        // GET: Survey/Create
        public ActionResult Create()
        {

            return View();
        }

        // POST: Survey/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(SurveyViewModel collection)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var userAuth = Trisatech.MWorkforce.Cms.Helpers.AppCookieHelper.Get<UserAuthenticated>(this.HttpContext);

                    // TODO: Add insert logic here
                    SurveyModel surveyModel = new SurveyModel();

                    CopyProperty.CopyPropertiesTo(collection, surveyModel);
                    surveyModel.SurveyId = Guid.NewGuid().ToString();
                    surveyModel.StartDate = collection.StartDate.ToUniversalTime();
                    surveyModel.EndDate = collection.EndDate.ToUniversalTime();

                    surveyService.Add(surveyModel, userAuth.UserId);
                    return RedirectToAction(nameof(Index));
                }
                catch(Exception ex)
                {
                    ViewBag.ErrorMessage = ex.Message;
                }
            }

            return View(collection);
        }

        // GET: Survey/Edit/5
        public ActionResult Edit(string id)
        {
            if (string.IsNullOrEmpty(id))
            {
                return NotFound();
            }

            var result = surveyService.Get(id);
            if(result == null)
            {
                return NotFound();
            }

            SurveyViewModel surveyViewModel = new SurveyViewModel();
            CopyProperty.CopyPropertiesTo(result, surveyViewModel);
            surveyViewModel.StartDate.ToLocalTime();
            surveyViewModel.EndDate.ToLocalTime();

            return View(surveyViewModel);
        }

        // POST: Survey/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(string id, SurveyViewModel collection)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var userAuth = Trisatech.MWorkforce.Cms.Helpers.AppCookieHelper.Get<UserAuthenticated>(this.HttpContext);

                    // TODO: Add update logic here
                    SurveyModel surveyModel = new SurveyModel();
                    CopyProperty.CopyPropertiesTo(collection, surveyModel);

                    surveyModel.SurveyId = id;
                    surveyModel.StartDate = collection.StartDate.ToUniversalTime();
                    surveyModel.EndDate = collection.EndDate.ToUniversalTime();

                    surveyService.Edit(surveyModel, userAuth.UserId);

                    return RedirectToAction(nameof(Index));
                }
                catch(Exception ex)
                {
                    ViewBag.ErrorMessage = ex.Message;
                }
            }

            return View(collection);
        }
        
        // POST: Survey/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(string id)
        {
            try
            {
                var userAuth = Trisatech.MWorkforce.Cms.Helpers.AppCookieHelper.Get<UserAuthenticated>(this.HttpContext);

                surveyService.Delete(id, userAuth.UserId);
            }
            catch(Exception ex)
            {
                TempData["ErrorMessage"] = ex.Message;
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

Trisatech.MWorkforce.Cms/Views/Survey/Create.cshtml
@model Trisatech.MWorkforce.Cms.ViewModels.SurveyViewModel

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section CustomScripts{
    <script type="text/javascript">
        jQuery(document).ready(function () {
            var errorMessage = '@ViewBag.ErrorMessage';
            if (errorMessage != '') {
                $('#errMessageTxt').text(errorMessage);
                $('#failedDialog').modal('show');
            }
        });
    </script>
}

<div class="page-content">
    <!-- BEGIN PAGE HEADER-->
    <!-- BEGIN PAGE HEAD -->
    
    
    <!-- END PAGE HEAD -->
    <!-- BEGIN PAGE BREADCRUMB -->
    <ul class="page-breadcrumb breadcrumb">
        <li>
            <a href="#">Survey</a>
            <i class="fa fa-circle"></i>
        </li>
        <li>
            <a href="#">Manage survey</a>
            <i class="fa fa-circle"></i>
        </li>
        <li>
            <a href="#">Add new survey</a>
        </li>
    </ul>
    <!-- END PAGE BREADCRUMB -->
	  <!-- BEGIN PAGE TITLE -->
    <div class="page-head">
        <div class="page-title">
            <h1>Survey</h1>
        </div>
    </div>
        <!-- END PAGE TITLE -->
        <!-- END PAGE HEADER-->
        <!-- BEGIN PAGE CONTENT-->
        <div class="row">
            <div class="col-md-12">
                <div class="portlet light bordered">
                    @*<div class="portlet-title">
                        <div class="caption">
                            <span class="caption-subject bold uppercase">Add new survey</span>
                        </div>
                    </div>*@
                    <div class="portlet-body form">
                        <form asp-action="create" class="form-horizontal form-row-seperated">
                            <div class="form-body">
                                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                                <div class="form-group">
                                    <label asp-for="SurveyName" class="control-label col-md-3"></label>
                                    <div class="col-md-5">
                                        <input asp-for="SurveyName" class="form-control" />
                                        <span asp-validation-for="SurveyName" class="text-danger"></span>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label asp-for="SurveyLink" class="control-label col-md-3"></label>
                                    <div class="col-md-5">
                                        <input asp-for="SurveyLink" class="form-control" />
                                        <span asp-validation-for="SurveyLink" class="text-danger"></span>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label asp-for="StartDate" class="control-label col-md-3"></label>
                                    <div class="col-md-5">
                                        <input asp-for="StartDate" type="date" class="form-control" />
                                        <span asp-validation-for="StartDate" class="text-danger"></span>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label asp-for="EndDate" class="control-label col-md-3"></label>
                                    <div class="col-md-5">
                                        <input asp-for="EndDate" type="date" class="form-control" />
                                        <span asp-validation-for="EndDate" class="text-danger"></span>
                                    </div>
                                </div>
                            </div>
                            <br />
                            <div class="form-actions">
                                <div class="row">
                                    <div class="col-md-offset-3 col-md-9">
                                        <a class="btn btn-padd2 grey-cascade" asp-action="index">Cancel</a>
                                        <button type="submit" class="btn btn-padd2 green" style="margin-left: 10px;">Submit</button>
                                    </div>
                                </div>
                            </div>
                        </form>
                        <!-- END FORM-->
                    </div>
                </div>
            </div>
        </div>
        <!-- END PAGE CONTENT-->
    </div>

Trisatech.MWorkforce.Cms/Views/Survey/Details.cshtml
@model Trisatech.MWorkforce.Cms.ViewModels.SurveyViewModel

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<form asp-action="delete">
	<div class="modal fade" id="confirmDelete" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		<div class="pos_middle">
			<div class="modal-dialog modal-sm">
				<div class="modal-content">
					<div class="modal-body" style="padding: 20px 25px;">
						<h4 class="text-center font-grey-gallery" style="font-weight: 600;">Are you sure to delete this ?</h4>
						<br />
						<input type="hidden" value="@Model.SurveyId" name="id" />
						<div class="row">
							<div class="col-md-6">
								<button type="submit" class="btn btn-block green uppercase" data-backdrop="static" data-keyboard="false">Yes</button>
							</div>
							<div class="col-md-6">
								<a href="#" class="btn btn-block red uppercase" data-backdrop="static" data-keyboard="false" data-dismiss="modal">No</a>
							</div>
						</div>
					</div>
				</div>
				<!-- /.modal-content -->
			</div>
		</div>
		<!-- /.modal-dialog -->
	</div>
</form>
<div class="page-content">
	<!-- BEGIN PAGE HEADER-->
	<!-- BEGIN PAGE HEAD -->
	
	
	<!-- END PAGE HEAD -->
	<!-- BEGIN PAGE BREADCRUMB -->
	<ul class="page-breadcrumb breadcrumb">
		<li>
			<a asp-action="Index">Manage Product</a>
			<i class="fa fa-circle"></i>
		</li>
		<li>
			<a asp-controller="Survey" asp-action="Details" asp-route-id="@Model.SurveyId">@Model.SurveyName</a>
		</li>
	</ul>
	<!-- END PAGE BREADCRUMB -->
	<!-- BEGIN PAGE TITLE -->
    <div class="page-head">
        <div class="page-title">
            <h1>Detail Survey</h1>
        </div>
    </div>
        <!-- END PAGE TITLE -->
        <!-- END PAGE HEADER-->
        <!-- BEGIN PAGE CONTENT-->
        <div class="row">
            <div class="col-md-12">
                <div class="portlet light bordered">
                    @*<div class="portlet-title">
                        <div class="caption">
                            <span class="caption-subject bold ">Survey</span>
                        </div>
                    </div>*@
                    <div class="row">
                        <div class="col-md-12">
                            <div class="content-detail">
                                <!-- Data User -->
                                <div class="portlet light bordered">
                                    <div class="portlet-title  text-right">
                                        <!-- ACTION BUTTON-->
                                        <div class="caption col-md-12">
                                            <div class="row">
                                                <div class="col-md-12">
                                                    <a class="btn btn-padd2 red" data-backdrop="static" data-keyboard="false" data-dismiss="modal" data-toggle="modal" data-target="#confirmDelete" href="#confirmDelete"><i class="fa fa-trash-o" aria-hidden="true"></i></a>
                                                    <a class="btn btn-padd2 green" asp-action="edit" asp-controller="survey" asp-route-id="@Model.SurveyId"><i class="fa fa-pencil" aria-hidden="true"></i></a>
                                                </div>
                                            </div>
                                        </div>
                                        <!--END ACTION BUTTON-->
                                    </div>
                                    <div class="portlet-body form">
                                        <!-- BEGIN FORM-->
                                        <form action="#" class="form-horizontal">
                                            <div class="portlet-body form">
                                                <div class="form-horizontal form-row-seperated">
                                                    <div class="form-body">
                                                        <div class="form-group">
                                                            <label class="control-label col-md-3">Name</label>
                                                            <div class="col-md-5">
                                                                <label class="control-label" style="color:black;">@Html.DisplayFor(model => model.SurveyName)</label>
                                                                <span class="text-danger"></span>
                                                            </div>
                                                        </div>
                                                        <div class="form-group">
                                                            <label class="control-label col-md-3">Google Form Link</label>
                                                            <div class="col-md-5">
                                                                <label class="control-label" style="color:black;"><a href="@Html.DisplayFor(model => model.SurveyLink)">@Html.DisplayFor(model => model.SurveyLink)</a></label>
                                                                <span class="text-danger"></span>
                                                            </div>
                                                        </div>
                                                        <div class="form-group">
                                                            <label class="control-label col-md-3">Start date</label>
                                                            <div class="col-md-5">
                                                                <label class="control-label" style="color:black;">@Model.StartDate.ToUtcID()</label>
                                                                <span class="text-danger"></span>
                                                            </div>
                                                        </div>
                                                        <div class="form-group">
                                                            <label class="control-label col-md-3">end date</label>
                                                            <div class="col-md-5">
                                                                <label class="control-label" style="color:black;">@Model.EndDate.ToUtcID()</label>
                                                                <span class="text-danger"></span>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="form-actions text-right">
                                                <div class="row">
                                                    <div class="col-md-offset-3 col-md-9">
                                                        <a class="btn btn-padd2 grey-cascade" asp-action="index">Back</a>
                                                    </div>
                                                </div>
                                            </div>
                                        </form>
                                        <!-- END FORM-->
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div>
                    </div>
                </div>
            </div>
        </div>
        <!-- END PAGE CONTENT-->
    </div>

Trisatech.MWorkforce.Cms/Views/Survey/Edit.cshtml
@model Trisatech.MWorkforce.Cms.ViewModels.SurveyViewModel

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@section CustomScripts{
    <script type="text/javascript">
        jQuery(document).ready(function () {
            var errorMessage = '@ViewBag.ErrorMessage';
            if (errorMessage != '') {
                $('#errMessageTxt').text(errorMessage);
                $('#failedDialog').modal('show');
            }
        });
    </script>
}

<div class="page-content">
    <!-- BEGIN PAGE HEADER-->
    <!-- BEGIN PAGE HEAD -->
    
    
    <!-- END PAGE HEAD -->
    <!-- BEGIN PAGE BREADCRUMB -->
    <ul class="page-breadcrumb breadcrumb">
        <li>
            <a href="#">Survey</a>
            <i class="fa fa-circle"></i>
        </li>
        <li>
            <a href="#">Manage survey</a>
            <i class="fa fa-circle"></i>
        </li>
        <li>
            <a href="#">Update survey</a>
        </li>
    </ul>
    <!-- END PAGE BREADCRUMB -->
	<!-- BEGIN PAGE TITLE -->
    <div class="page-head">
        <div class="page-title">
            <h1>Survey</h1>
        </div>
    </div>
        <!-- END PAGE TITLE -->
        <!-- END PAGE HEADER-->
        <!-- BEGIN PAGE CONTENT-->
        <div class="row">
            <div class="col-md-12">
                <div class="portlet light bordered">
                    @*<div class="portlet-title">
                        <div class="caption">
                            <span class="caption-subject bold ">Update survey</span>
                        </div>
                    </div>*@
                    <div class="portlet-body form">
                        <form asp-action="edit" class="form-horizontal form-row-seperated">
                            <div class="form-body">
                                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                                <div class="form-group">
                                    <label asp-for="SurveyName" class="control-label col-md-3"></label>
                                    <div class="col-md-5">
                                        <input asp-for="SurveyName" class="form-control" />
                                        <span asp-validation-for="SurveyName" class="text-danger"></span>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label asp-for="SurveyLink" class="control-label col-md-3"></label>
                                    <div class="col-md-5">
                                        <input asp-for="SurveyLink" class="form-control" />
                                        <span asp-validation-for="SurveyLink" class="text-danger"></span>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label asp-for="StartDate" class="control-label col-md-3"></label>
                                    <div class="col-md-5">
                                        <input asp-for="StartDate" type="date" class="form-control" />
                                        <span asp-validation-for="StartDate" class="text-danger"></span>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label asp-for="EndDate" class="control-label col-md-3"></label>
                                    <div class="col-md-5">
                                        <input asp-for="EndDate" type="date" class="form-control" />
                                        <span asp-validation-for="EndDate" class="text-danger"></span>
                                    </div>
                                </div>
                            </div>
                            <br />
                            <div class="form-actions">
                                <div class="row">
                                    <div class="col-md-offset-3 col-md-9">
                                        <a class="btn btn-padd2 grey-cascade" asp-action="index">Cancel</a>
                                        <button type="submit" class="btn btn-padd2 green" style="margin-left: 10px;">Submit</button>
                                    </div>
                                </div>
                            </div>
                        </form>
                        <!-- END FORM-->
                    </div>
                </div>
            </div>
        </div>
        <!-- END PAGE CONTENT-->
    </div>

Trisatech.MWorkforce.Cms/Views/Survey/Index.cshtml
@model IEnumerable<Trisatech.MWorkforce.Cms.ViewModels.SurveyViewModel>
@using Trisatech.MWorkforce.Cms.Helpers

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section Styles{
    <link rel="stylesheet" type="text/css" href="~/lib/select2-old/select2.css" />
    <link rel="stylesheet" type="text/css" href="~/lib/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.css" />
}

@section Scripts{
    <!-- BEGIN PAGE LEVEL PLUGINS -->
    <script type="text/javascript" src="~/lib/select2-old/select2.min.js"></script>
    <script type="text/javascript" src="~/lib/plugins/datatables/media/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="~/lib/plugins/datatables/extensions/TableTools/js/dataTables.tableTools.min.js"></script>
    <script type="text/javascript" src="~/lib/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.js"></script>
    <!-- END PAGE LEVEL PLUGINS -->
}
@section CustomScripts{
    <script type="text/javascript">
        var urlDataTable = '@SiteHelper.GetBaseUrl(this.Context.Request)/ajaxdatatable/surveys';
    </script>
    <!--- BEGIN CUSTOM JAVASCRIPT -->
    <script src="~/js/survey-datatable.js" type="text/javascript"></script>
    <script>
        var baseUrl = '@SiteHelper.GetBaseUrl(this.Context.Request)'

        $(document).on("click", ".btn-delete", function () {
            var id = $(this).data('id');
            $(".modal-body #itemId").val(id);
        });

    </script>
    <!-- END JAVASCRIPTS -->
}
    <div class="page-content">
        <!-- BEGIN SAMPLE PORTLET CONFIGURATION MODAL FORM-->
        <!-- Confirm Alert -->
        <form asp-action="delete" method="post">
            <div class="modal fade" id="confirmDelete" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                <div class="pos_middle">
                    <div class="modal-dialog modal-sm">
                        <div class="modal-content">
                            <div class="modal-body" style="padding: 20px 25px;">
                                <!-- <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button> -->
                                <h4 class="text-center font-grey-gallery" style="font-weight: 600;">Are you sure to delete this item?</h4>
                                <br />
                                <div class="row">
                                    <input type="hidden" id="itemId" name="id" />
                                    <div class="col-md-6">
                                        <button type="submit" class="btn btn-block green uppercase" data-backdrop="static" data-keyboard="false">Ya</button>
                                    </div>
                                    <div class="col-md-6">
                                        <a href="#" class="btn btn-block red uppercase" data-backdrop="static" data-keyboard="false" data-dismiss="modal">Cancel</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- /.modal-content -->
                    </div>
                </div>
                <!-- /.modal-dialog -->
            </div>
        </form>
        <!-- /.modal -->
        <!-- END SAMPLE PORTLET CONFIGURATION MODAL FORM-->
        <!-- BEGIN PAGE HEADER-->
        <!-- BEGIN PAGE BREADCRUMB -->
        <ul class="page-breadcrumb breadcrumb">
            <li>
                <a asp-action="index">Home</a>
                <i class="fa fa-circle"></i>
            </li>
            <li>
                <a href="#">Survey</a>
            </li>
        </ul>
        <!-- END PAGE BREADCRUMB -->
        <!-- BEGIN PAGE HEAD -->
        <div class="page-head">
            <!-- BEGIN PAGE TITLE -->
            <div class="page-title">
                <h1>Survey</h1>
            </div>
            <!-- END PAGE TITLE -->
        </div>
        <!-- END PAGE HEAD -->
        <!-- END PAGE HEADER-->
        <!-- BEGIN PAGE CONTENT-->
        <div class="row">
            <div class="col-md-12">
                <div class="portlet light bordered">
                    @*<div class="portlet-title">
                        <div class="caption">
                            <span class="caption-subject bold uppercase">Manage Survey</span>
                        </div>
                        <a class="btn btn-padd1 green pull-right" href="@SiteHelper.GetBaseUrl(this.Context.Request)/survey/create"><i class="fa fa-plus"></i> &nbsp Add New Survey</a>
                    </div>*@
                    <div class="portlet-body">
                        @*<div class="portlet box green">
                            <div class="portlet-title">
                                <div class="tools">
                                    <a href="javascript:;" class="collapse" data-original-title="" title="">
                                    </a>
                                </div>
                            </div>*@
                            <div class="portlet-body cust-table separate">
                                <div class="table-scrollable">
                                    <a class="btn btn-padd1 green pull-right" href="@SiteHelper.GetBaseUrl(this.Context.Request)/survey/create"> New Survey</a>
                                    <table class="table table-hover datatable_original" id="table-list">
                                        <thead>
                                            <tr>
                                                <th>
                                                    No
                                                </th>
                                                <th>
                                                    @Html.DisplayNameFor(model => model.SurveyName)
                                                </th>
                                                <th>
                                                    @Html.DisplayNameFor(model => model.SurveyLink)
                                                </th>
                                                <th>
                                                    @Html.DisplayNameFor(model => model.StartDate)
                                                </th>
                                                <th>
                                                    @Html.DisplayNameFor(model => model.EndDate)
                                                </th>
                                            </tr>
                                        </thead>
                                        <tbody></tbody>
                                    </table>
                                </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
        <!-- END PAGE CONTENT-->
    </div>